spring:
  application:
    name: shoppingonline
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_system?useSSL=false&serverTimezone=UTC
    username: root
    password:
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.keshe.entity


logging:
  level:
    com.example.keshe.mapper.UserHomeMapper: debug
